global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'connectme-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'backend'
          env: 'prod'

  - job_name: 'connectme-bot'
    metrics_path: /metrics
    static_configs:
      - targets: ['bot:8001']
        labels:
          service: 'bot'
          env: 'prod'

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
